### PR TITLE
Find pinocchio through CMake.

### PR DESCRIPTION
**Pull request by skasperski**

### CODE REVIEW

**Comment by skasperski** [comment]
@dmronga

**Comment by dmronga** [comment]
Do you know why it is failing with pkgconfig file? I prefer to use pkgconfig, and it used to be working fine

**Comment by dmronga** [comment]
Looks ok to me

**Comment by skasperski** [comment]
> Do you know why it is failing with pkgconfig file? I prefer to use pkgconfig, and it used to be working fine

Their package-config file is completely broken. Maybe it was ok in the past, or it's generation is now failing due to other changes in our autoproj-environment. 

```
prefix=${pcfiledir}/../..
exec_prefix=${pcfiledir}/../..
libdir=${pcfiledir}/../../lib
bindir=${pcfiledir}/../../bin
pkglibdir=${pcfiledir}/../../lib/pinocchio
includedir=${pcfiledir}/../../include
datarootdir=${pcfiledir}/../../share
pkgdatarootdir=${pcfiledir}/../../share
docdir=
doxygendocdir=

Name: pinocchio
Description: A fast and flexible implementation of Rigid Body Dynamics algorithms and their analytical derivatives
URL: http://github.com/stack-of-tasks/pinocchio
Version: 2.6.9
Requires: eigen3 >= 3.0.5, urdfdom >= 0.2.0
Conflicts: 
Libs: -L${libdir}  -lpinocchio -L/usr/lib/x86_64-linux-gnu -lboost_filesystem -lboost_serialization -lboost_system
Libs.private: 
Cflags:  -I${includedir} -DPINOCCHIO_WITH_URDFDOM
```

**Pull request merged**
